addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"               % "3.9.21")
addSbtPlugin("com.github.sbt"  % "sbt-pgp"                    % "2.1.2")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"               % "2.4.6")
addSbtPlugin("com.github.sbt"  % "sbt-ci-release"             % "1.5.12")
addSbtPlugin("com.github.sbt"  % "sbt-site-paradox"           % "1.5.0")
addSbtPlugin("io.github.jonas" % "sbt-paradox-material-theme" % "0.6.0")
addSbtPlugin("com.github.sbt"  % "sbt-ghpages"                % "0.8.0")
addSbtPlugin("com.typesafe"    % "sbt-mima-plugin"            % "1.1.3")
