name: ci

on:
  pull_request:
    branches-ignore:
      - main
      - gh-pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build and Test
        run: sbt -v "+scalafmtCheckAll;+test;"
      - name: Binary Compatibility Check
        run: sbt +mimaReportBinaryIssues
      - name: Run Cats Effect Example
        env:
          UNSTRUCTURED_API_KEY: ${{ secrets.UNSTRUCTURED_API_KEY }}
        run: |
          sbt "examples/runMain org.twelvehart.unstructured4s.examples.CatsEffectApp" 
